on: push
name: Build and Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - run: go version
      - run: go mod tidy
      - run: GOOS=linux GOARCH=arm GOARM=7 go build -o smart-analog-intercom.arm64
      - run: GOOS=linux go build -o smart-analog-intercom.amd64
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            smart-analog-intercom.arm64
            smart-analog-intercom.amd64